### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by emberian** [durka/closet#4]
# Why?

The MIT license requires reproducing countless copies of the same copyright
header with different names in the copyright field, for every MIT library in
use. The Apache license does not have this drawback, and has protections from
patent trolls and an explicit contribution licensing clause. However, the
Apache license is incompatible with GPLv2. This is why Rust is dual-licensed as
MIT/Apache (the "primary" license being Apache, MIT only for GPLv2 compat), and
doing so would be wise for this project. This also makes this crate suitable
for inclusion in the Rust standard distribution and other project using dual
MIT/Apache.
# How?

To do this, get explicit approval from each contributor of copyrightable work
(as not all contributions qualify for copyright) and then add the following to
your README:

```
## License

Licensed under either of
 * Apache License, Version 2.0 ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)
at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you shall be dual licensed as above, without any
additional terms or conditions.
```

and in your license headers, use the following boilerplate (based on that used in Rust):

```
// Copyright (c) 2015 t developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT
// license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
```

And don't forget to update the `license` metadata in your `Cargo.toml`!
# Contributor checkoff
- [ ] @durka

**Comment by durka** [comment]
I would encourage you not to make these kinds of autogenerated posts.

Anyway... I don't really understand the rationale here. If the strongest motivation to switch to Apache is to unclutter other people's LICENSE files... dammit, I'm just going to switch to the WTFPL.

**Comment by emberian** [comment]
WTFPL should _never_ be used if you want others to use your software.

That isn't the strongest motivation, the strongest motivation intrinsic to the license is the patent protection and explicit contribution clause. The other motivation is the ability to freely share code with the rest of the Rust ecosystem, including the standard distribution.

**Comment by durka** [comment]
From my point of view (wanting to deal with licensing and patents as little as possible) the Apache license is longer and more complicated. I don't hold any software patents so I have none to grant. Also, I'm skeptical about the license repetition thing. Apache requires people to state the modifications that they've made, which seems _more_ cumbersome.

That said, I'm still willing to be convinced.

**Comment by emberian** [comment]
Stating modifications is only required per-file and only when redistributing in source-form (not binary).

I agree that the Apache license is long and cumbersome (though less so than the GPL...), and the issues around "intellectual property" and open source are ridiculous and obnoxious. But, it's the reality we live in.

**Comment by durka** [comment]
I guess I'm just going to end up doing it to minimize friction with the rest of the Rust ecosystem. I'll trust that the core devs have made a good decision.

Can I leave the boilerplate out of the files, and just put it in LICENSE? Last I saw, rustc has them in every file mostly due to inertia.

**Comment by emberian** [comment]
Yeah, I don't really know why boilerplate is necessary. I won't officially recommend either way, but a lot of people do leave the boilerplate out.

**Comment by durka** [comment]
Thanks @cmr. I apologize for my initially grumpy reaction.

**Comment by emberian** [comment]
@durka no problem. software licensing is obnoxious.
